# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170127_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='billhistoryline',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billhistoryline',
            name='line',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='legislativebody',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='district',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='other_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
