# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agenda_item',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('bill_type', models.CharField(max_length=1024, null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('text', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
        migrations.CreateModel(
            name='BillHistoryLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Bill')),
            ],
            options={
                'db_table': 'bill_history_line',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='LegislativeBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'legislative_body',
            },
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('district', models.CharField(max_length=256, null=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('legislative_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.LegislativeBody')),
            ],
            options={
                'db_table': 'legislator',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=1024, null=True)),
                ('name', models.CharField(max_length=1024, null=True)),
                ('other_info', models.TextField(null=True)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('legislative_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.LegislativeBody')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=1024, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_string', models.CharField(max_length=256)),
                ('sponsor_type', models.CharField(choices=[('SP', 'Sponsor'), ('CO', 'Co-sponsor')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Bill')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Legislator')),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Place')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='legislativebody',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Place'),
        ),
        migrations.AddField(
            model_name='city',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Place'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.State'),
        ),
        migrations.AddField(
            model_name='bill',
            name='legislative_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.LegislativeBody'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Bill'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legislation_models.Meeting'),
        ),
    ]
