# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0003_auto_20170127_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='place',
        ),
        migrations.AddField(
            model_name='meeting',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
