# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0003_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='query_params',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
