# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0004_auto_20170127_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='legislative_body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legislation_models.LegislativeBody'),
            preserve_default=False,
        ),
    ]
