# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0004_auto_20170205_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='notification',
            field=models.CharField(choices=[('none', 'do not notify me'), ('daily', 'notify me daily'), ('weekly', 'notify me weekly')], default='none', max_length=24),
        ),
    ]
