# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0005_search_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='city',
        ),
        migrations.RemoveField(
            model_name='search',
            name='state',
        ),
    ]
