# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0006_auto_20170205_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='place',
            field=models.TextField(null=True),
        ),
    ]
