# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0008_search_notify_on_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='last_notify_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
