# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation_models', '0009_search_last_notify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='full_text_link',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
